In [1]:
import pandas as pd
import numpy as np
import scipy
from scipy.sparse import find
import scipy.stats
import os
import scipy.io as sio
import scipy.ndimage
import dnatools
%matplotlib inline
from pylab import *

# Plotting Params:
rc('mathtext', default='regular')
fsize=20

In [2]:
data = sio.loadmat('/Users/niyanth/Documents/data_gz/Reads.mat')
# A5SS
A5SS_data = data['A5SS']
A5SS_reads = np.array(A5SS_data.sum(1)).flatten()
A5SS_data = np.array(A5SS_data.todense())
# Get minigenes with reads
A5SS_nn = find(A5SS_data.sum(axis=1))

A5SS_reads = A5SS_reads[A5SS_nn[1]]
A5SS_data = A5SS_data[A5SS_nn[1]]
A5SS_data = A5SS_data/A5SS_data.sum(axis=1)[:,newaxis]
A5SS_seqs = pd.read_csv('/Users/niyanth/Documents/data_gz/A5SS_Seqs.csv',index_col=0).Seq[A5SS_nn[1]]

In [238]:
A5SS_data.shape

(265044, 304)

In [205]:
A5SS_nn

(array([0, 0, 0, ..., 0, 0, 0], dtype=int32),
 array([     0,      1,      2, ..., 265134, 265135, 265136], dtype=int32),
 array([26., 46., 19., ..., 50., 35., 55.]))

In [188]:
A5SS_nn1 = []
for i in range(len(A5SS_nn[2])):
    A5SS_nn1.append(int(A5SS_nn[2][i]))

In [223]:
A5SS_reads = np.array(A5SS_data.sum(1)).flatten()
A5SS_reads

array([26., 46., 19., ..., 50., 35., 55.])

In [224]:
A5SS_reads = np.array(A5SS_data.sum(1))
A5SS_reads

array([26., 46., 19., ..., 50., 35., 55.])

In [184]:
A5SS_nn[2][0] = int(A5SS_nn[2][0])
A5SS_nn[2][0]

26.0

In [194]:
A5SS_reads = np.array(A5SS_data.sum(1)).flatten()
A5SS_reads[0]

1.0

In [221]:
np.array(A5SS_data.sum(1)).flatten()

array([26., 46., 19., ..., 50., 35., 55.])

In [199]:
print(A5SS_data)

  (1, 0)	5.0
  (2, 0)	4.0
  (3, 0)	109.0
  (4, 0)	5.0
  (6, 0)	1.0
  (8, 0)	11.0
  (10, 0)	1.0
  (12, 0)	8.0
  (13, 0)	67.0
  (14, 0)	1.0
  (15, 0)	34.0
  (16, 0)	16.0
  (17, 0)	3.0
  (18, 0)	5.0
  (19, 0)	1.0
  (20, 0)	10.0
  (21, 0)	3.0
  (22, 0)	161.0
  (24, 0)	1.0
  (26, 0)	103.0
  (27, 0)	1.0
  (28, 0)	3.0
  (30, 0)	1.0
  (31, 0)	1.0
  (32, 0)	11.0
  :	:
  (265107, 303)	8.0
  (265108, 303)	3.0
  (265109, 303)	3.0
  (265110, 303)	5.0
  (265111, 303)	4.0
  (265113, 303)	2.0
  (265114, 303)	2.0
  (265115, 303)	5.0
  (265119, 303)	4.0
  (265120, 303)	8.0
  (265121, 303)	5.0
  (265122, 303)	4.0
  (265123, 303)	1.0
  (265124, 303)	1.0
  (265125, 303)	2.0
  (265126, 303)	6.0
  (265127, 303)	4.0
  (265128, 303)	3.0
  (265129, 303)	4.0
  (265131, 303)	2.0
  (265132, 303)	3.0
  (265133, 303)	3.0
  (265134, 303)	2.0
  (265135, 303)	3.0
  (265136, 303)	4.0


In [3]:
def make_padded_nmer_matrix(seqs,mer_len):
    mer_dict = dict(zip(dnatools.make_mer_list(6),range(4**6)))
    rows,cols,vals = [],[],[]
    for i in range(len(seqs)):
        cur_seq = A5SS_seqs[i]
        for b in [*range(7-mer_len,32), *range(50-mer_len,75)]:
            cur_mer = cur_seq[b:b+mer_len]
            cur_mer_list_pos = mer_dict[cur_mer]
            rows.append(i)
            cols.append(cur_mer_list_pos+4**mer_len*(b+80))
            vals.append(1)
        if(i%10000)==0:
            print (i,)
            
        # Add a zero to the bottom right of the matrix to ensure the
        # correct size
        rows.append(len(A5SS_data)-1)
        cols.append(4**6*230-1)
        vals.append(0)
    X = scipy.sparse.csr_matrix((vals,(rows,cols)))
    return X

In [4]:
X = make_padded_nmer_matrix(A5SS_seqs,6)


0
10000
20000
30000
40000
50000
60000
70000
80000
90000
100000
110000
120000
130000
140000
150000
160000
170000
180000
190000
200000
210000
220000
230000
240000
250000
260000


In [5]:
print(X)

  (0, 335455)	1
  (0, 338301)	1
  (0, 341495)	1
  (0, 346076)	1
  (0, 352112)	1
  (0, 355779)	1
  (0, 358156)	1
  (0, 363570)	1
  (0, 364744)	1
  (0, 369443)	1
  (0, 375948)	1
  (0, 377395)	1
  (0, 383180)	1
  (0, 385840)	1
  (0, 392384)	1
  (0, 393987)	1
  (0, 400396)	1
  (0, 401459)	1
  (0, 405708)	1
  (0, 410416)	1
  (0, 416962)	1
  (0, 418570)	1
  (0, 425000)	1
  (0, 426144)	1
  (0, 430720)	1
  :	:
  (265043, 540292)	1
  (265043, 543251)	1
  (265043, 546895)	1
  (265043, 549181)	1
  (265043, 554228)	1
  (265043, 558033)	1
  (265043, 565061)	1
  (265043, 568596)	1
  (265043, 570451)	1
  (265043, 573772)	1
  (265043, 578866)	1
  (265043, 582857)	1
  (265043, 586534)	1
  (265043, 593048)	1
  (265043, 594528)	1
  (265043, 600450)	1
  (265043, 603659)	1
  (265043, 608303)	1
  (265043, 610494)	1
  (265043, 615163)	1
  (265043, 621548)	1
  (265043, 626611)	1
  (265043, 630479)	1
  (265043, 633661)	1
  (265043, 942079)	0


In [6]:
Y = scipy.matrix(A5SS_data)

In [7]:
Y = scipy.hstack((Y[:,:80],Y[:,-1:]))


<ipython-input-7-dcea77943f82>:1: DeprecationWarning: scipy.hstack is deprecated and will be removed in SciPy 2.0.0, use numpy.hstack instead
  Y = scipy.hstack((Y[:,:80],Y[:,-1:]))


In [247]:
X.shape

(265044, 942080)

In [249]:
Y.shape

(265044, 81)

In [8]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X,Y,test_size=0.2)



In [ ]:
from sklearn.linear_model import LinearRegression

reg = LinearRegression().fit(X, Y)
reg.score(X, Y)

In [ ]:
#                                                   Logistic Regression

from sklearn.linear_model import LogisticRegression

log_clf = LogisticRegression(random_state=0)
log_clf.fit(x_train, y_train)
prediction = log_clf.predict(x_test)
accuracy = metrics.accuracy_score(y_test, prediction)
probability = log_clf.predict_proba(x_test)
print("accuracy: " +str(accuracy))

In [ ]:
#                                                  SVC

svc_clf = SVC()
svc_clf.fit(x_train, y_train)
prediction = svc_clf.predict(x_test)
accuracy = metrics.accuracy_score(y_test,prediction)
print("accuracy: " + str(accuracy))

In [ ]:
#                                                  KNN

neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(x_train, y_train)
prediction = neigh.predict(x_test)
accuracy = metrics.accuracy_score(y_test,prediction)
print("accuracy: " + str(accuracy))


In [9]:
#                                                  CNN

import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

# If you would like to make further imports from Tensorflow, add them here
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Conv2D, MaxPooling2D
from tensorflow.keras.preprocessing import image

In [264]:
x_train.shape

(212035, 942080)

In [ ]:
x_train = x_train[..., np.newaxis]
x_test = x_test[..., np.newaxis]

In [2]:
def get_model(input_shape):
    model = Sequential([
        Conv2D(8, (3,3), activation='relu', padding='same', input_shape= (212035, 942080, 1)),
        MaxPooling2D((2,2), padding='same'),
        Flatten(),
        Dense(64, activation='relu'),
        Dense(64, activation='relu'),
        Dense(10, activation='softmax'),
    ])
    return(model)

In [ ]:
model = get_model(x_train.shape)


In [ ]:
def compile_model(model):
    opt = tf.keras.optimizers.Adam()
    model.compile(optimizer=opt,
                 loss='sparse_categorical_crossentropy',
                 metrics = ['accuracy'])

In [ ]:
compile_model(model)

In [ ]:
def train_model(model, x_train, y_train):
    model.fit(x_train, y_train, epochs=5)

In [ ]:
history = train_model(model, x_train, y_train)

In [ ]:
def evaluate_model(model, x_test, y_test):
    model.evaluate(x_test, y_test, verbose=2)

In [ ]:
test_loss, test_accuracy = evaluate_model(model, x_test, y_test)
print(f"Test loss: {test_loss}")
print(f"Test accuracy: {test_accuracy}")

In [60]:
arr = np.array(A5SS_seqs)
print(arr[0])
string = str(arr[0])
len(string)
string

['TGCTTGGTGAAGACAGAGAAAGAGAACCAAAAGGTCGACCCAGGTTCGTGAATCCGGTAACGCGGAGAGAATACAGAGGTATTCTTATCACCTTCGTGGCT']


"['TGCTTGGTGAAGACAGAGAAAGAGAACCAAAAGGTCGACCCAGGTTCGTGAATCCGGTAACGCGGAGAGAATACAGAGGTATTCTTATCACCTTCGTGGCT']"

In [37]:
np.sum(A5SS_reads, axis = 0)

13257452.0

In [66]:
A5SS_data

array([[ 0.,  0.,  0., ...,  0.,  0.,  4.],
       [ 5.,  0.,  0., ...,  0.,  0., 22.],
       [ 4.,  0.,  0., ...,  0.,  0.,  4.],
       ...,
       [44.,  0.,  0., ...,  0.,  0.,  2.],
       [ 0.,  0.,  0., ...,  0.,  0.,  3.],
       [ 1.,  0.,  0., ...,  0.,  0.,  4.]])

In [67]:
A5SS_reads

array([26., 46., 19., ..., 50., 35., 55.])

In [68]:
A5SS_seqs

Seq
Tag                                                                              
CATTACCTGCGCCCTTTCCGCCCTTATCTA  TGCTTGGTGAAGACAGAGAAAGAGAACCAAAAGGTCGACCCAGGTT...
CATTACCTGCTTTAACCTTCTCGCCTTATC  TGCTTGGTAAACAGGTTAAGGAACGTAACAATGGTCGACCCAGGTT...
CATTACCTGCAACTACCCTCCTGTTCGTAA  TGCTTGGTTGAGAGCTGAGCTCACACAGGGTGGGTCGACCCAGGTT...
CATTACCTGCGTTTTCACCGGCCGCTTAGA  TGCTTGGGAGAAAGGGCGGGGAAGGGAAAGCAGGTCGACCCAGGTT...
CATTACCTGCCTGTACTTGACCTATTTGAT  TGCTTGGGTACGGATAGGAAGGGGACACAGGGGGTCGACCCAGGTT...
...                                                                           ...
CATTACCTGCATGCCGGCACACTCCCCCGC  TGCTTGGAAGGGTTGAAATACATACGGGTAACGGTCGACCCAGGTT...
CATTACCTGCGAAACCCTGCCTCTAGTCCA  TGCTTGGTTTATGGTGGTGGAGAGAGAGCAGGGGTCGACCCAGGTT...
CATTACCTGCCGGCTTGGAGTACCCCTCCT  TGCTTGGGTAATGAATCGGGTGGAGAAAAACGGGTCGACCCAGGTT...
CATTACCTGCGACCACACGCTCTGGTCCAC  TGCTTGGATGCGGTCAAGAAGGGATAGGTACCGGTCGACCCAGGTT...
CATTACCTGCCTTCTTGTGCGGCCTGTCCC  TGCTTGGGGTCCGCGCATCGTTCACAAAGGAAGGTCGACCCAGGTT...

[265137 rows x 1 columns]

In [88]:
A5SS_seqs.describe()

Seq
count                                              265137
unique                                             264201
top     TGCTTGGACGAGACTAGGGGATAGGGGATCGGGGTCGACCCAGGTT...
freq                                                    5

In [76]:
arr

array([['TGCTTGGTGAAGACAGAGAAAGAGAACCAAAAGGTCGACCCAGGTTCGTGAATCCGGTAACGCGGAGAGAATACAGAGGTATTCTTATCACCTTCGTGGCT'],
       ['TGCTTGGTAAACAGGTTAAGGAACGTAACAATGGTCGACCCAGGTTCGTGGATATTTATCGTAACTGACATCATGGAGGTATTCTTATCACCTTCGTGGCT'],
       ['TGCTTGGTTGAGAGCTGAGCTCACACAGGGTGGGTCGACCCAGGTTCGTGCGCTACGAAAGAAGATACCGCAAGCGAGGTATTCTTATCACCTTCGTGGCT'],
       ...,
       ['TGCTTGGGTAATGAATCGGGTGGAGAAAAACGGGTCGACCCAGGTTCGTGCGAGGCACGAGTACAAAGACGAAATGAGGTATTCTTATCACCTTCGTGGCT'],
       ['TGCTTGGATGCGGTCAAGAAGGGATAGGTACCGGTCGACCCAGGTTCGTGCGAGCCCACGACTCAGGCCTAATATGAGGTATTCTTATCACCTTCGTGGCT'],
       ['TGCTTGGGGTCCGCGCATCGTTCACAAAGGAAGGTCGACCCAGGTTCGTGGGCCATAGGTATTAGACTCAACGGCGAGGTATTCTTATCACCTTCGTGGCT']],
      dtype=object)

In [81]:
A5SS_seqs

Seq
Tag                                                                              
CATTACCTGCGCCCTTTCCGCCCTTATCTA  TGCTTGGTGAAGACAGAGAAAGAGAACCAAAAGGTCGACCCAGGTT...
CATTACCTGCTTTAACCTTCTCGCCTTATC  TGCTTGGTAAACAGGTTAAGGAACGTAACAATGGTCGACCCAGGTT...
CATTACCTGCAACTACCCTCCTGTTCGTAA  TGCTTGGTTGAGAGCTGAGCTCACACAGGGTGGGTCGACCCAGGTT...
CATTACCTGCGTTTTCACCGGCCGCTTAGA  TGCTTGGGAGAAAGGGCGGGGAAGGGAAAGCAGGTCGACCCAGGTT...
CATTACCTGCCTGTACTTGACCTATTTGAT  TGCTTGGGTACGGATAGGAAGGGGACACAGGGGGTCGACCCAGGTT...
...                                                                           ...
CATTACCTGCATGCCGGCACACTCCCCCGC  TGCTTGGAAGGGTTGAAATACATACGGGTAACGGTCGACCCAGGTT...
CATTACCTGCGAAACCCTGCCTCTAGTCCA  TGCTTGGTTTATGGTGGTGGAGAGAGAGCAGGGGTCGACCCAGGTT...
CATTACCTGCCGGCTTGGAGTACCCCTCCT  TGCTTGGGTAATGAATCGGGTGGAGAAAAACGGGTCGACCCAGGTT...
CATTACCTGCGACCACACGCTCTGGTCCAC  TGCTTGGATGCGGTCAAGAAGGGATAGGTACCGGTCGACCCAGGTT...
CATTACCTGCCTTCTTGTGCGGCCTGTCCC  TGCTTGGGGTCCGCGCATCGTTCACAAAGGAAGGTCGACCCAGGTT...

[265137 rows x 1 columns]

In [85]:
A5SS_seqs[1][0]

'TGCTTGGTAAACAGGTTAAGGAACGTAACAATGGTCGACCCAGGTTCGTGGATATTTATCGTAACTGACATCATGGAGGTATTCTTATCACCTTCGTGGCT'